"""Cron runner: execute every feature graph, commit outputs, continue
past failures (FR-827 R-5 cron machine: running -> succeeded |
failed_recorded, never starve the rest).

CLI: python -m tools.cron_run [date]
Exit 1 if any feature failed (all features still attempted).
"""

import json
import os
import re
import selectors
import signal
import stat
import subprocess
import sys
import time
from pathlib import Path

FOOTER = (
    "\n---\n*generated by [gitclaw](https://github.com/sheikkinen/gitclaw), "
    "powered by [yamlgraph](https://github.com/sheikkinen/yamlgraph)*\n"
)
MAX_CANDIDATE_BYTES = 32 * 1024
MAX_ENVELOPE_BYTES = 96 * 1024
MAX_MANIFEST_BYTES = 16 * 1024
MAX_PROCESS_STDOUT_BYTES = 512 * 1024
MAX_PROCESS_STDERR_BYTES = 64 * 1024
MAX_REASON_CHARS = 500
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
RESERVED_STATE_KEYS = {
    "_agent_iterations",
    "_agent_limit_reached",
    "_loop_counts",
    "_loop_limit_reached",
    "candidate",
    "current_step",
    "date",
    "errors",
    "messages",
    "run_instant",
    "source_snapshots",
}


class ManifestError(ValueError):
    pass


def _strict_object(pairs):
    obj = {}
    for key, value in pairs:
        if key in obj:
            raise ManifestError(f"duplicate key: {key}")
        obj[key] = value
    return obj


def load_manifest(feature_dir: Path) -> tuple[str, ...] | None:
    path = feature_dir / "composition.json"
    try:
        descriptor = os.open(path, os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW)
    except FileNotFoundError:
        try:
            path.lstat()
        except FileNotFoundError:
            return None
        raise ManifestError("manifest must be a non-symlink regular file") from None
    except OSError as exc:
        raise ManifestError("manifest must be a non-symlink regular file") from exc
    try:
        path_stat = os.fstat(descriptor)
        if not stat.S_ISREG(path_stat.st_mode):
            raise ManifestError("manifest must be a non-symlink regular file")
        if path_stat.st_size > MAX_MANIFEST_BYTES:
            raise ManifestError(f"manifest exceeds {MAX_MANIFEST_BYTES} bytes")
        raw = os.read(descriptor, MAX_MANIFEST_BYTES + 1)
    finally:
        os.close(descriptor)
    if len(raw) > MAX_MANIFEST_BYTES:
        raise ManifestError(f"manifest exceeds {MAX_MANIFEST_BYTES} bytes")
    try:
        manifest = json.loads(raw.decode("utf-8"), object_pairs_hook=_strict_object)
    except json.JSONDecodeError as exc:
        raise ManifestError(f"invalid JSON: {exc.msg}") from exc
    if not isinstance(manifest, dict):
        raise ManifestError("manifest must be an object")
    unknown = set(manifest) - {"version", "dependencies"}
    if unknown:
        raise ManifestError(f"unknown key: {sorted(unknown)[0]}")
    if type(manifest.get("version")) is not int or manifest["version"] != 1:
        raise ManifestError("version must be integer 1")
    dependencies = manifest.get("dependencies")
    if not isinstance(dependencies, list):
        raise ManifestError("dependencies must be a list")
    if not dependencies:
        raise ManifestError("dependencies must be non-empty")
    seen = set()
    for dependency in dependencies:
        if not isinstance(dependency, str) or not SLUG_RE.fullmatch(dependency):
            raise ManifestError("dependency must be a canonical feature slug")
        if dependency in seen:
            raise ManifestError(f"duplicate dependency: {dependency}")
        seen.add(dependency)
    return tuple(dependencies)


def _coerce(value, key: str) -> str | None:
    if isinstance(value, str) and value.strip():
        return value
    if isinstance(value, dict):
        inner = value.get(key)
        if isinstance(inner, str) and inner.strip():
            return inner
        if len(value) == 1:
            only = next(iter(value.values()))
            if isinstance(only, str) and only.strip():
                return only
    return None


def _coerce_candidate(value) -> str | None:
    if isinstance(value, str) and value.strip():
        return value
    if isinstance(value, dict) and set(value) == {"candidate"}:
        candidate = value["candidate"]
        if isinstance(candidate, str) and candidate.strip():
            return candidate
    return None


def extract_output(state: dict, feature: str) -> str | None:
    text = _coerce(state.get(feature), feature)
    if text is not None:
        return text
    text = _coerce_candidate(state.get("candidate"))
    if text is not None:
        return text
    # generated graphs pick their own state_key; accept a lone
    # self-named candidate, fail closed on zero or many
    candidates = [
        _coerce(v, k)
        for k, v in state.items()
        if k not in RESERVED_STATE_KEYS and isinstance(v, dict) and k in v
    ]
    candidates = [c for c in candidates if c is not None]
    return candidates[0] if len(candidates) == 1 else None


def run_feature(
    graph: Path, date: str, extra_vars: dict[str, str] | None = None
) -> tuple[bool, str]:
    """Returns (ok, text): output text on success, reason on failure."""
    command = [
        "yamlgraph",
        "graph",
        "run",
        str(graph),
        "--var",
        f"date={date}",
    ]
    for key, value in (extra_vars or {}).items():
        command.extend(["--var", f"{key}={value}"])
    command.append("--json")
    returncode, stdout_bytes, stderr_bytes, process_error = _run_bounded(command)
    if process_error:
        return False, process_error
    try:
        stdout = stdout_bytes.decode("utf-8")
        stderr = stderr_bytes.decode("utf-8", errors="replace")
    except UnicodeDecodeError:
        return False, "non-UTF-8 stdout"
    if returncode != 0:
        return False, f"exit {returncode}: {stderr[-MAX_REASON_CHARS:]}"
    try:
        state = json.loads(stdout)
    except json.JSONDecodeError:
        return False, f"non-JSON stdout: {stdout[-MAX_REASON_CHARS:]}"
    text = extract_output(state, graph.parent.name)
    if text is None:
        # failed LLM nodes exit 0 with the error only in state
        return False, f"no output in state: {list(state.keys())}"
    return True, text


def _run_bounded(
    command: list[str], timeout: int = 600
) -> tuple[int | None, bytes, bytes, str | None]:
    try:
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            start_new_session=True,
        )
    except OSError as exc:
        return None, b"", b"", f"spawn failed: {exc}"

    selector = selectors.DefaultSelector()
    streams = {process.stdout: "stdout", process.stderr: "stderr"}
    for stream, name in streams.items():
        os.set_blocking(stream.fileno(), False)
        selector.register(stream, selectors.EVENT_READ, name)
    stdout = bytearray()
    stderr = bytearray()
    deadline = time.monotonic() + timeout
    error = None
    try:
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                error = f"timeout after {timeout}s"
                break
            if not selector.get_map():
                if process.poll() is not None:
                    try:
                        os.killpg(process.pid, 0)
                    except ProcessLookupError:
                        break
                    error = "descendant processes outlived graph"
                    break
                time.sleep(min(0.05, remaining))
                continue
            for key, _ in selector.select(remaining):
                chunk = os.read(key.fileobj.fileno(), 65536)
                if not chunk:
                    selector.unregister(key.fileobj)
                    continue
                target = stdout if key.data == "stdout" else stderr
                limit = (
                    MAX_PROCESS_STDOUT_BYTES
                    if key.data == "stdout"
                    else MAX_PROCESS_STDERR_BYTES
                )
                target.extend(chunk)
                if len(target) > limit:
                    error = f"{key.data} exceeds {limit} bytes"
                    break
            if error:
                break
    finally:
        selector.close()
        if error:
            try:
                os.killpg(process.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        process.wait()
    return process.returncode, bytes(stdout), bytes(stderr), error


def _cycle_errors(
    dependencies: dict[str, tuple[str, ...] | None], errors: dict[str, str]
) -> dict[str, str]:
    state = {}
    active = []
    positions = {}
    for root in sorted(dependencies):
        if root in errors or state.get(root, 0) != 0:
            continue
        stack = [(root, 0)]
        while stack:
            name, index = stack[-1]
            if state.get(name, 0) == 0:
                state[name] = 1
                positions[name] = len(active)
                active.append(name)
            declared = dependencies.get(name) or ()
            if index < len(declared):
                dependency = declared[index]
                stack[-1] = (name, index + 1)
                if dependency in errors:
                    continue
                dependency_state = state.get(dependency, 0)
                if dependency_state == 0:
                    stack.append((dependency, 0))
                elif dependency_state == 1:
                    start = positions[dependency]
                    cycle = active[start:] + [dependency]
                    reason = "dependency cycle: " + " -> ".join(cycle)
                    for member in cycle[:-1]:
                        errors.setdefault(member, reason)
                continue
            stack.pop()
            active.pop()
            positions.pop(name)
            state[name] = 2
    return errors


def _validate_features(
    graphs: dict[str, Path],
) -> tuple[dict[str, tuple[str, ...] | None], dict[str, str]]:
    dependencies = {}
    errors = {}
    for name, graph in graphs.items():
        try:
            dependencies[name] = load_manifest(graph.parent)
        except (ManifestError, OSError, UnicodeError) as exc:
            dependencies[name] = None
            errors[name] = f"invalid composition.json: {exc}"

    for name in sorted(dependencies):
        if name in errors:
            continue
        declared = dependencies[name]
        if declared is None:
            continue
        if name in declared:
            errors[name] = f"self-dependency: {name}"
            continue
        for dependency in declared:
            if dependency not in graphs:
                errors[name] = f"missing dependency: {dependency}"
                break

    _cycle_errors(dependencies, errors)
    changed = True
    while changed:
        changed = False
        for name in sorted(dependencies):
            if name in errors:
                continue
            for dependency in dependencies[name] or ():
                if dependency in errors:
                    errors[name] = f"unavailable dependency: {dependency}"
                    changed = True
                    break
    return dependencies, errors


def _execution_order(
    dependencies: dict[str, tuple[str, ...] | None], errors: dict[str, str]
) -> list[str]:
    runnable = {name for name in dependencies if name not in errors}
    remaining = {
        name: sum(dependency in runnable for dependency in dependencies[name] or ())
        for name in runnable
    }
    dependents = {name: [] for name in runnable}
    for name in runnable:
        for dependency in dependencies[name] or ():
            if dependency in runnable:
                dependents[dependency].append(name)
    ready = sorted(name for name, count in remaining.items() if count == 0)
    order = []
    while ready:
        order.extend(ready)
        next_ready = []
        for name in ready:
            for dependent in dependents[name]:
                remaining[dependent] -= 1
                if remaining[dependent] == 0:
                    next_ready.append(dependent)
        ready = sorted(next_ready)
    return order


def _failure_entry(feature: str, reason: str) -> dict[str, str]:
    return {
        "feature": feature,
        "status": "failed",
        "reason": reason[-MAX_REASON_CHARS:],
    }


def _source_envelope(
    declared: tuple[str, ...], results: dict[str, tuple[bool, str]]
) -> tuple[bool, str]:
    encoded_entries = []
    encoded_size = 2
    for dependency in declared:
        ok, text = results[dependency]
        if ok:
            entry = {
                "feature": dependency,
                "status": "succeeded",
                "candidate": text,
            }
        else:
            entry = _failure_entry(dependency, text)
        encoded_entry = json.dumps(entry, ensure_ascii=False, separators=(",", ":"))
        encoded_size += len(encoded_entry.encode("utf-8"))
        if encoded_entries:
            encoded_size += 1
        if encoded_size > MAX_ENVELOPE_BYTES:
            return False, f"source_snapshots exceeds {MAX_ENVELOPE_BYTES} UTF-8 bytes"
        encoded_entries.append(encoded_entry)
    return True, "[" + ",".join(encoded_entries) + "]"


def _record_result(name: str, date: str, ok: bool, text: str) -> None:
    if ok:
        Path(f"outputs/{date}-{name}.md").write_text(text + "\n" + FOOTER)
        print(f"succeeded: {name}")
    else:
        record = {"feature": name, "date": date, "reason": text[-MAX_REASON_CHARS:]}
        Path(f"outputs/{date}-{name}.failed.json").write_text(json.dumps(record) + "\n")
        print(f"failed_recorded: {name}: {record['reason']}", file=sys.stderr)


def main(date: str | None = None) -> int:
    date = date or time.strftime("%Y-%m-%d", time.gmtime())
    Path("outputs").mkdir(exist_ok=True)
    graphs = {
        graph.parent.name: graph
        for graph in sorted(Path("features").glob("*/graph.yaml"))
    }
    dependencies, validation_errors = _validate_features(graphs)
    results = {}
    failures = len(validation_errors)
    for name in sorted(validation_errors):
        reason = validation_errors[name]
        results[name] = (False, reason)
        _record_result(name, date, False, reason)

    for name in _execution_order(dependencies, validation_errors):
        graph = graphs[name]
        declared = dependencies[name]
        if declared is None:
            ok, text = run_feature(graph, date)
        else:
            envelope_ok, envelope = _source_envelope(declared, results)
            if envelope_ok:
                ok, text = run_feature(graph, date, {"source_snapshots": envelope})
            else:
                ok, text = False, envelope
        if ok and len(text.encode("utf-8")) > MAX_CANDIDATE_BYTES:
            ok = False
            text = f"candidate exceeds {MAX_CANDIDATE_BYTES} UTF-8 bytes"
        results[name] = (ok, text)
        _record_result(name, date, ok, text)
        if not ok:
            failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else None))
